### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 52: ordinal not in range(128)

### ISSUE THREAD

**Issue by ovpn-to** [ovpn-to/oVPN.to-Client-Software#114]
Traceback (most recent call last):
  File "ovpn_client.py", line 5936, in <module>
  File "ovpn_client.py", line 5932, in app
  File "ovpn_client.py", line 97, in __init__
  File "ovpn_client.py", line 318, in preboot
  File "ovpn_client.py", line 971, in read_interfaces
  File "ovpn_client.py", line 995, in win_read_interfaces
  File "winregs.pyo", line 56, in get_networkadapterlist
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 52: ordinal not in range(128)

> name of my network adapter is the default of portuguese based windows operational systems "Conexão Local"

**Comment by ovpn-to** [comment]
workaround yet: rename networkadapters to "lan1" "lan2" "wifi1" "wifi2" "vpn1" "vpn2" ... without non ascii chars :(

**Comment by ovpn-to** [comment]
fixed
